-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3308
-- Generation Time: Jul 05, 2024 at 12:03 PM
-- Server version: 8.0.31
-- PHP Version: 7.4.33

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `recipie`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

DROP TABLE IF EXISTS `recipes`;
CREATE TABLE IF NOT EXISTS `recipes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(30) NOT NULL,
  `authorid` varchar(30) NOT NULL,
  `description` longtext NOT NULL,
  `ingredients` longtext NOT NULL,
  `steps` longtext NOT NULL,
  `image` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `title`, `authorid`, `description`, `ingredients`, `steps`, `image`) VALUES
(4, 'Ramen', '56789', 'This Ramen recipe brings the authentic flavors of Japan to your kitchen with a rich broth, chewy noodles, and a variety of delicious toppings.', '4 cups chicken or vegetable broth\r\n2 tbsp soy sauce\r\n1 tbsp miso paste\r\n1 tbsp sesame oil\r\n2 cloves garlic, minced\r\n1-inch ginger, minced\r\n2 packs ramen noodles\r\n1 cup sliced mushrooms\r\n1 cup spinach\r\n2 boiled eggs, halved\r\n1/4 cup sliced green onions\r\n1/4 cup corn kernels\r\n1/4 cup shredded carrots\r\nSeaweed, for garnish', 'In a large pot, heat the sesame oil over medium heat and sauté the garlic and ginger until fragrant.\r\nAdd the broth, soy sauce, and miso paste, and bring to a simmer.\r\nAdd the mushrooms and cook for 5 minutes.\r\nCook the ramen noodles according to package instructions and set aside.\r\nDivide the noodles between bowls and pour the hot broth over them.\r\nTop with spinach, boiled eggs, green onions, corn, carrots, and seaweed.\r\nServe immediately and enjoy your delicious homemade ramen!', 'ramen.jpg'),
(2, 'Oreo Shake', '12345', 'This Oreo Shake is a delicious and refreshing drink, perfect for any time of the day. Made with creamy ice cream and crushed Oreos, it\'s a treat that you can make in minutes!', '4 scoops of vanilla ice cream 8 Oreo cookies 1 cup of milk Whipped cream Crushed Oreos for topping', 'Place the vanilla ice cream, Oreo cookies, and milk in a blender. Blend until smooth and creamy. Pour the shake into glasses. Top with whipped cream and crushed Oreos. Serve immediately and enjoy!', 'oreo.jpg'),
(3, 'Rainbow Cake', '67890', 'This Rainbow Cake is a show-stopping dessert with vibrant layers of cake and a creamy frosting. It\'s perfect for birthdays, parties, or any festive occasion!', '2 cups all-purpose flour 1 1/2 cups sugar 1 cup unsalted butter, softened 4 large eggs 1 cup milk 2 tsp baking powder 1 tsp vanilla extract Food coloring (red, orange, yellow, green, blue, purple) Frosting of your choice', 'Preheat your oven to 350°F (175°C) and grease six 8-inch round cake pans. In a large bowl, cream the butter and sugar until light and fluffy. Add the eggs one at a time, beating well after each addition. Stir in the vanilla extract. Combine the flour and baking powder, add to the creamed mixture alternately with the milk, mixing until just incorporated. Divide the batter evenly into six bowls and add a different food coloring to each bowl, mixing until the desired color is achieved. Pour each colored batter into the prepared cake pans and bake for 15-20 minutes, or until a toothpick inserted into the center comes out clean. Allow the cakes to cool in the pans for 10 minutes, then turn them out onto a wire rack to cool completely. Once the cakes are completely cool, stack them with a layer of frosting between each cake layer, starting with purple at the bottom and working your way up to red. Frost the outside of the cake with the remaining frosting and decorate as desired. Slice and enjoy your colorful Rainbow Cake!', 'cake.jpg'),
(5, 'Chicken Salad', '123456789', 'This refreshing Chicken Salad is a perfect blend of tender chicken, crisp vegetables, and a creamy dressing. It\'s an easy-to-make dish that is both nutritious and delicious, ideal for a quick lunch or a light dinner. Enjoy this versatile salad on its own, as a sandwich filling, or served over greens.', 'For the Salad:\r\n2 cups cooked chicken breast, diced or shredded\r\n1 cup celery, finely chopped\r\n1 cup red grapes, halved\r\n1/2 cup red onion, finely diced\r\n1/2 cup apple, diced (Granny Smith or any tart variety)\r\n1/4 cup toasted almonds, sliced or slivered\r\n1/4 cup dried cranberries\r\n1/4 cup fresh parsley, chopped\r\nSalt and pepper to taste\r\nFor the Dressing:\r\n1/2 cup mayonnaise\r\n2 tablespoons Greek yogurt\r\n1 tablespoon Dijon mustard\r\n1 tablespoon lemon juice\r\n1 teaspoon honey\r\n1/4 teaspoon garlic powder\r\nSalt and pepper to taste', 'Prepare the Ingredients:\r\nDice or shred the cooked chicken breast and place it in a large mixing bowl.\r\nFinely chop the celery, red onion, and apple. Halve the red grapes.\r\nToast the sliced almonds in a dry skillet over medium heat until golden brown, about 2-3 minutes. Allow them to cool.\r\n\r\nMake the Dressing:\r\nIn a small bowl, whisk together the mayonnaise, Greek yogurt, Dijon mustard, lemon juice, honey, and garlic powder until well combined. Season with salt and pepper to taste.\r\n\r\nAssemble the Salad:\r\nAdd the chopped celery, red grapes, red onion, apple, toasted almonds, dried cranberries, and fresh parsley to the bowl with the chicken.\r\nPour the dressing over the salad ingredients. Gently toss everything together until the salad is evenly coated with the dressing.\r\n\r\nSeason and Adjust:\r\nTaste the salad and add salt and pepper as needed. You can also adjust the sweetness by adding more honey or tartness by adding more lemon juice.\r\n\r\nServe:\r\nServe the chicken salad immediately or chill in the refrigerator for 30 minutes to allow the flavors to meld. It can be enjoyed on its own, as a sandwich filling, or over a bed of greens.\r\n\r\nStore:\r\nStore any leftovers in an airtight container in the refrigerator for up to 3 days. Stir before serving as the dressing may separate slightly.', 'chicken-salad.jpg'),
(6, 'Paneer Butter Masala', '57373', 'Paneer Butter Masala is a rich and creamy North Indian curry made with paneer (Indian cottage cheese) cooked in a tomato-based gravy with butter and cream. It\'s a delicious and indulgent dish that\'s perfect for serving with naan, roti, or rice. The dish is known for its aromatic spices and smooth, velvety texture, making it a favorite in Indian cuisine.', 'For the Paneer Butter Masala:\r\n200 grams paneer, cubed\r\n2 tablespoons butter\r\n1 tablespoon oil\r\n1 large onion, finely chopped\r\n2 large tomatoes, pureed\r\n1 tablespoon ginger-garlic paste\r\n1 green chili, finely chopped (optional)\r\n1/2 teaspoon turmeric powder\r\n1 teaspoon red chili powder\r\n1 teaspoon coriander powder\r\n1/2 teaspoon garam masala\r\n1/2 teaspoon cumin powder\r\n1/4 cup heavy cream\r\n1 teaspoon kasuri methi (dried fenugreek leaves), crushed\r\n1 tablespoon honey or sugar\r\nSalt to taste\r\nFresh cilantro (coriander) leaves, chopped, for garnish\r\n\r\nFor the Cashew Paste:\r\n10-12 cashew nuts\r\n1/4 cup warm water', 'Prepare the Cashew Paste:\r\nSoak the cashew nuts in warm water for about 15 minutes.\r\nBlend the soaked cashews into a smooth paste using a little water. Set aside.\r\n\r\nCook the Paneer:\r\nHeat 1 tablespoon of butter and oil in a pan over medium heat.\r\nAdd the paneer cubes and lightly fry until golden brown on all sides.\r\nRemove the paneer and set aside on a paper towel to drain excess oil.\r\n\r\nPrepare the Masala Base:\r\nIn the same pan, add the remaining butter.\r\nAdd finely chopped onions and sauté until they turn golden brown.\r\nAdd ginger-garlic paste and sauté for 2-3 minutes until the raw smell disappears.\r\nAdd finely chopped green chili (if using) and mix well.\r\n\r\nAdd Spices and Tomato Puree:\r\nAdd turmeric powder, red chili powder, coriander powder, and cumin powder. Mix well and cook for a minute.\r\nPour in the tomato puree and cook until the oil starts to separate from the masala, stirring occasionally. This usually takes about 5-7 minutes.\r\n\r\nIncorporate Cashew Paste and Paneer:\r\nAdd the prepared cashew paste to the pan and mix well.\r\nCook for another 2-3 minutes until the mixture is well combined.\r\nAdd the fried paneer cubes and stir gently to coat them with the masala.\r\n\r\nFinish with Cream and Spices:\r\nAdd garam masala and crushed kasuri methi to the pan.\r\nPour in the heavy cream and stir gently to combine.\r\nAdd honey or sugar and salt to taste. Adjust the consistency with a little water if needed.\r\n\r\nSimmer and Serve:\r\nLet the paneer butter masala simmer for 3-4 minutes on low heat, allowing the flavors to meld together.\r\nGarnish with fresh cilantro leaves.\r\n\r\nServe Hot:\r\nServe the Paneer Butter Masala hot with naan, roti, or steamed rice. Enjoy the rich and creamy flavors!', 'paneer.jpg'),
(7, 'Alfredo Pasta', '37954', 'Creamy Alfredo Pasta is a classic Italian dish that features a rich and velvety sauce made with butter, heavy cream, and Parmesan cheese. This simple yet indulgent recipe delivers a luscious, cheesy flavor that\'s perfect for a comforting meal. It pairs beautifully with fettuccine or any pasta of your choice and can be enhanced with additional ingredients like garlic, chicken, or vegetables.', 'For the Alfredo Sauce:\r\n2 tablespoons unsalted butter\r\n2 cloves garlic, minced (optional)\r\n1 cup heavy cream\r\n1 cup grated Parmesan cheese\r\n1/4 teaspoon black pepper\r\n1/4 teaspoon salt\r\n1/4 teaspoon ground nutmeg (optional)\r\n2 tablespoons chopped fresh parsley, for garnish\r\n\r\nFor the Pasta:\r\n250 grams (8 oz) fettuccine or pasta of your choice\r\nSalt for pasta water\r\n1 tablespoon olive oil (optional)\r\n\r\nOptional Add-ins:\r\nGrilled chicken breast, sliced\r\nSteamed broccoli florets\r\nSautéed mushrooms', 'Cook the Pasta:\r\nFill a large pot with water, add a generous amount of salt, and bring it to a boil.\r\nAdd the fettuccine or pasta of your choice and cook according to the package instructions until al dente.\r\nDrain the pasta, reserving about 1/2 cup of the pasta water, and set aside. You can add a tablespoon of olive oil to prevent the pasta from sticking together.\r\n\r\nPrepare the Alfredo Sauce:\r\nIn a large skillet, melt the butter over medium heat.\r\nAdd minced garlic (if using) and sauté for 1-2 minutes until fragrant, but not browned.\r\nPour in the heavy cream and bring to a gentle simmer. Let it simmer for 2-3 minutes, stirring occasionally.\r\n\r\nAdd Parmesan Cheese:\r\nGradually whisk in the grated Parmesan cheese until the sauce is smooth and the cheese is fully melted.\r\nSeason with black pepper, salt, and a pinch of ground nutmeg (if using).\r\nContinue to simmer for another 2-3 minutes, allowing the sauce to thicken slightly.\r\n\r\nCombine Pasta and Sauce:\r\nAdd the cooked pasta to the skillet and toss to coat it evenly with the Alfredo sauce.\r\nIf the sauce is too thick, add a little of the reserved pasta water to reach your desired consistency.\r\n\r\nIncorporate Optional Add-ins:\r\nIf using, add grilled chicken slices, steamed broccoli, or sautéed mushrooms to the pasta and mix well.\r\n\r\nGarnish and Serve:\r\nSprinkle freshly chopped parsley over the pasta for a burst of color and flavor.\r\nServe the Creamy Alfredo Pasta hot, garnished with extra Parmesan cheese if desired.\r\n\r\nEnjoy:\r\nPlate the pasta and enjoy the rich, creamy, and cheesy goodness of your homemade Alfredo Pasta!', 'alfredo.jpg'),
(8, 'Baked Chicken', '13475', 'Baked Chicken is a simple, yet flavorful dish that is perfect for any meal. This recipe provides juicy, tender chicken with a crispy, golden-brown skin. It’s an easy and healthy option for both weeknight dinners and special occasions.', '4 chicken breasts (bone-in, skin-on)\r\n2 tablespoons olive oil\r\n1 teaspoon salt\r\n1/2 teaspoon black pepper\r\n1 teaspoon garlic powder\r\n1 teaspoon paprika\r\n1 teaspoon dried thyme\r\n1 teaspoon dried rosemary\r\n1 lemon, sliced\r\n2 cloves garlic, minced\r\nFresh parsley, for garnish', 'Preheat the Oven: Preheat your oven to 400°F (200°C).\r\n\r\nPrepare the Chicken:\r\nPat the chicken breasts dry with paper towels.\r\nPlace them in a large baking dish or on a baking sheet.\r\n\r\nSeason the Chicken:\r\nDrizzle the olive oil over the chicken breasts.\r\nSprinkle the salt, black pepper, garlic powder, paprika, dried thyme, and dried rosemary evenly over the chicken.\r\nRub the seasonings into the chicken to ensure an even coating.\r\n\r\nAdd Lemon and Garlic:\r\nArrange the lemon slices around and under the chicken breasts.\r\nSprinkle the minced garlic over the chicken and lemons.\r\n\r\nBake the Chicken:\r\nPlace the baking dish or sheet in the preheated oven.\r\nBake for 35-40 minutes, or until the chicken reaches an internal temperature of 165°F (74°C) and the skin is golden brown and crispy.\r\nUse a meat thermometer to check the temperature for accuracy.\r\n\r\nRest the Chicken:\r\nRemove the chicken from the oven.\r\nLet it rest for about 5-10 minutes before serving. This helps the juices redistribute throughout the meat, making it juicier.\r\n\r\nGarnish and Serve:\r\nGarnish the baked chicken with fresh parsley.\r\nServe it with your favorite side dishes, such as roasted vegetables, mashed potatoes, or a fresh green salad.\r\n\r\nEnjoy:\r\nEnjoy your delicious and healthy Baked Chicken!', 'baked.jpg'),
(9, 'Avocado Toast', '66385', 'Avocado Toast is a quick, easy, and healthy breakfast or snack option that combines the creamy texture of ripe avocado with the crunch of toasted bread. It\'s a versatile dish that can be customized with a variety of toppings such as eggs, tomatoes, or even a sprinkle of red pepper flakes for an extra kick. This recipe is perfect for those who are looking for a nutritious start to their day or a light meal that\'s ready in minutes.', '2 slices of whole grain bread: Whole grain bread provides a nutty flavor and extra fiber, making it a healthy choice.\r\n1 ripe avocado: The star of the dish, avocados are packed with healthy fats and give a creamy texture.\r\n1 tablespoon of lemon juice: Adds a refreshing tanginess and prevents the avocado from browning.\r\nSalt and pepper to taste: Essential seasonings to enhance the flavor.\r\nOptional toppings:\r\n1 poached egg: Adds protein and richness.\r\nCherry tomatoes, halved: For a burst of sweetness.\r\nRed pepper flakes: For a bit of heat.\r\nFresh herbs (like cilantro or basil): Adds a fresh and aromatic finish.', 'Toast the bread:\r\n\r\nPlace the slices of whole grain bread in a toaster and toast them until they are golden brown and crispy.\r\nPrepare the avocado:\r\n\r\nCut the avocado in half and remove the pit.\r\nScoop the flesh into a bowl and mash it with a fork until smooth.\r\nAdd lemon juice, salt, and pepper to the mashed avocado and mix well.\r\nAssemble the toast:\r\n\r\nSpread the mashed avocado evenly over each slice of toasted bread.\r\nMake sure to cover the entire surface for a consistent flavor in every bite.\r\nAdd toppings (optional):\r\n\r\nFor a classic touch, place a poached egg on top of the avocado spread.\r\nAdd cherry tomato halves for sweetness and color.\r\nSprinkle with red pepper flakes if you like a bit of spice.\r\nGarnish with fresh herbs like cilantro or basil for an aromatic finish.\r\nServe immediately:\r\n\r\nEnjoy your Avocado Toast while the bread is still warm and crispy.\r\nServe it as a quick breakfast, a healthy snack, or even a light lunch.\r\nVariations:\r\n\r\nYou can customize your Avocado Toast with other toppings such as crumbled feta cheese, sliced radishes, or smoked salmon for a more gourmet experience.', 'avocado.jpg'),
(10, 'Egg Fried Rice', '006', 'A quick and easy classic dish that\'s perfect for a midweek meal. Egg Fried Rice is a versatile recipe that can be customized with your favorite vegetables and proteins. This version keeps it simple, allowing the flavors of the egg and soy sauce to shine through.', 'Rice\r\n3 cups cooked white rice (preferably chilled)\r\nEggs\r\n2 large eggs\r\nVegetables\r\n1/2 cup carrots, diced\r\n1/2 cup peas (fresh or frozen)\r\n1/2 cup corn kernels (fresh or frozen)\r\n1/4 cup green onions, chopped\r\n1/4 cup bell pepper, diced (optional)\r\nAromatics\r\n2 cloves garlic, minced\r\n1 tablespoon ginger, minced (optional)\r\nSeasonings\r\n3 tablespoons soy sauce (adjust to taste)\r\n1 tablespoon oyster sauce (optional)\r\n1 teaspoon sesame oil (optional)\r\nSalt and pepper, to taste\r\nOils\r\n2 tablespoons vegetable oil or cooking oil of choice\r\nOptional Garnishes\r\nExtra chopped green onions\r\nSesame seeds\r\n', 'Preparation\r\nPrepare all the ingredients: dice the carrots, bell pepper, and green onions. If using fresh vegetables, cook them briefly until tender.\r\n\r\nCook the Eggs\r\nHeat 1 tablespoon of oil in a large skillet or wok over medium heat.\r\nBeat the eggs in a bowl, then pour into the skillet. Scramble the eggs until they are fully cooked. Remove and set aside.\r\n\r\nSauté the Vegetables\r\nIn the same skillet, add the remaining oil.\r\nAdd the garlic and ginger (if using) and sauté for about 30 seconds until fragrant.\r\nAdd the diced carrots, peas, corn, and bell pepper. Cook for about 2-3 minutes until they start to soften.\r\n\r\nAdd the Rice\r\nAdd the chilled rice to the skillet, breaking up any clumps. Stir-fry the rice with the vegetables for about 2-3 minutes, ensuring everything is well mixed and heated through.\r\n\r\nSeason and Combine\r\nAdd the soy sauce, oyster sauce (if using), and sesame oil to the skillet. Mix well to evenly coat the rice and vegetables.\r\nReturn the cooked eggs to the skillet. Stir everything together until the eggs are evenly distributed throughout the rice.\r\n\r\nAdjust Seasonings\r\nTaste and adjust the seasoning with salt and pepper as needed. You can add more soy sauce if you prefer a stronger flavor.\r\n\r\nServe\r\nRemove from heat and garnish with extra chopped green onions and sesame seeds if desired.\r\nServe the Egg Fried Rice hot as a main dish or a side.\r\n\r\nEnjoy!\r\nYour Egg Fried Rice is ready to be enjoyed! Serve it with your favorite Asian dishes or as a standalone meal.\r\n', 'fried-rice.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(30) NOT NULL,
  `mobile` varchar(30) NOT NULL,
  `email` varchar(30) NOT NULL,
  `password` varchar(100) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`id`, `username`, `mobile`, `email`, `password`) VALUES
(9, 'aarohi', '1234555', 'aarohi@sample.com', 'aarohi'),
(10, 'riddh', '123456', 'riddh@gmail.com', 'riddh'),
(8, 'admin', '1234567', 'admin@gmail.com', 'admin');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
